### ISSUE TITLE
target forwarding

### ISSUE THREAD

**Issue by kempy007** [eswdd/go-smee#1]
Hi I don't see how this replicates the nodejs smee client since I can't see where to configure the forwarding target, seems to be missing and cannot be done by setting the string.

**Comment by eswdd** [comment]
Hi,
To be honest, I barely remember even writing this, and certainly not what I wrote it for. I think I just wanted a smee client library in Go and probably thought there was no point writing something to forward to a target since I could just run the nodejs one if I wanted that. But can't be certain of course.

**Comment by kempy007** [comment]
Always a good day :)
